### ISSUE TITLE
Tutorial crashes during final segment

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-stream#1]
Occasionally accompanied by minor graphical issues (score and accuracy disappearing or corrupting)

Running iPhone SE on latest iOS (12.2)

**Comment by MillhioreF** [comment]
Just crashed again when returning to song select from the results screen after playing 6 maps or so. When I say "crash", I mean that the app freezes up entirely for 1-2 minutes while music continues to play, then eventually hard crashes back to home screen.

**Comment by peppy** [comment]
Fixed a while back :).
