### ISSUE TITLE
Grades on song page inside of score (iPad mini 4)

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu-stream#10]
More UI scaling stuff.
![E3F04DA1-558E-4F7F-BAE0-CCDE646328A6](https://user-images.githubusercontent.com/25379179/74954009-6b7eda80-53d0-11ea-9ede-77347cf909cb.png)
Kind of self-explanitory.

**Comment by peppy** [comment]
oops.

**Comment by peppy** [comment]
Fixed for next release!
