### ISSUE TITLE
Home bar overlaps level design credits.

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu-stream#11]
Also overlaps the bottom row controls at difficulty select screen. The home bar should be hidden. 

![ABE92882-82B6-4970-9D9A-CD18D4C82490](https://user-images.githubusercontent.com/45163894/74959411-d0c4e100-544d-11ea-873a-e3d1909c73e9.png)

**Comment by peppy** [comment]
We unfortunately can't hide this, but the overlap is fixed for next release!
