### ISSUE TITLE
Swiping the news popup offscreen freezes the game

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu-stream#12]
I don't know what to call the "news popup" exactly, but it's the window that pops up whenever you tap the "News" button on the main menu. Swiping it offscreen (instead of pressing "Done") freezes the game (or at least, on my device, anyways).
Video: https://streamable.com/vp1ao

The same thing happens with "Online Help" in the settings.

**Comment by peppy** [comment]
Fixed in next release (thanks to @timoliver).
