### ISSUE TITLE
Play Button beside songs in Store moves when scrolls offscreen

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu-stream#13]
i'm sorry but i found a thing
https://streamable.com/qzolp

also a screenshot:
![C2E429E5-6D13-4215-8446-03CA3538F27E](https://user-images.githubusercontent.com/25379179/75114993-d9254380-5628-11ea-8118-198b79e9aa9b.png)

**Comment by peppy** [comment]
Thanks, fixed for next build :).
