### ISSUE TITLE
All songs deleted every time the app is closed

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu-stream#14]
It seems that every time I force close osu!stream or have it closed for extended periods of time (like, an hour) it deletes all my downloaded songs. I'm not sure if it's an issue with my device, or if it's intended.

**Comment by peppy** [comment]
Do you happen to have low free disk space?

**Comment by AndyThePie** [comment]
You know what, yeah, that’s probably it. Freeing up some space seems to have solved the issue. 
Thank you!
