### ISSUE TITLE
Screen flickers and sliders have white lines when screensharing on Discord

### ISSUE THREAD

**Issue by the-source-hoarder** [ppy/osu-stream#21]
![s](https://user-images.githubusercontent.com/50369519/98573972-081b3c80-22c0-11eb-80e0-1149fdc43b6e.png)

**Comment by peppy** [comment]
Are you planning to fix this? If not, please do note the project readme - this is not a maintained project and for that reason we can't really support/accommodate bug reports like this.

**Comment by peppy** [comment]
Closing for now, please leave a message if you plan on attempting to fix your issue.
