### ISSUE TITLE
(Android) AudioEngine isn't defined in current context

### ISSUE THREAD

**Issue by anton2007** [ppy/osu-stream#31]
![Screenshot_20211231-151817_AnyDesk](https://user-images.githubusercontent.com/37032392/147812070-97410fc9-f5c3-486c-8602-30c2a1eecb9a.jpg)
I never tried building .NET apps and using Visual Studio and probably that's my error.

I have Xamarin pack installed in Visual Studio installer.
I just got AudioServer isn't defined errors when I tried building debug versions by openning .sln file and clicking "build solution" button

**Comment by peppy** [comment]
Probably just missing a `using` statement.
