### ISSUE TITLE
(Android) weird bug with new line/n

### ISSUE THREAD

**Issue by anton2007** [ppy/osu-stream#33]
![Screenshot_20220101-033344_osu!stream](https://user-images.githubusercontent.com/37032392/147838407-ccb2ed49-17be-4fe8-aa4d-9bfcc0568bf6.jpg)
I using Samsung Galaxy M12 with Android 11 (SDK API version 30) and experiencing weird bug...  new line character just doesn't work as expected.

**Comment by peppy** [comment]
This was an issue with the russian localisation. I've fixed it.
