### ISSUE TITLE
Publish android version to Play Store

### ISSUE THREAD

**Issue by rollingmoai** [ppy/osu-stream#38]
Tracking https://github.com/ppy/osu-stream/pull/27#issuecomment-1002511542
> It'd be a waste not to push this out to the google play store, so I will aim to do so sometime in 2022.

**Comment by Beyley** [comment]
There might be roadblocks to this happening currently according to https://github.com/ManagedBass/ManagedBass/issues/6, no one has attempted to publish an app using ManagedBass to the play store

**Comment by peppy** [comment]
I'm not sure why that would even be an issue in the first place.

**Comment by Beyley** [comment]
> I'm not sure why that would even be an issue in the first place.

not sure but i've heard people having bad times getting apps approved for menial reasons, and support being very unhelpful

**Comment by itsmeboy0** [comment]
> There might be roadblocks to this happening, according to [ManagedBass/ManagedBass#6](https://github.com/ManagedBass/ManagedBass/issues/6), no one has attempted to publish an app using ManagedBass to the play store

Well, we'll be the first to test that out then. I don't see a problem with that either.

**Comment by JJoshua04** [comment]
Try this  https://drive.google.com/file/d/1Odsu3W6y_nCc3p-Ifa35OQUy-D7B4k5P/view

**Comment by JJoshua04** [comment]
Try this https://drive.google.com/file/d/1AFoD78WebW9SHtIkHqn0SmTOF0zayRkJ/view?usp=sharing

**Comment by rollingmoai** [comment]
> Try this https://drive.google.com/file/d/1AFoD78WebW9SHtIkHqn0SmTOF0zayRkJ/view?usp=sharing

I have already compiled it myself, but thanks anyway.

**Comment by LukaTV939** [comment]
For those who are sharing the apk of the game, please don't and build it by yourself

**Comment by ThePooN** [comment]
Has been published today: https://play.google.com/store/apps/details?id=sh.ppy.osustream

**Comment by rollingmoai** [comment]
It would be good to add it to the readme
