### ISSUE TITLE
[Android] ability to load .osz2 beatmaps on a non-rooted device

### ISSUE THREAD

**Issue by Maritoguionyo** [ppy/osu-stream#49]
I wonder if it is possible like on a jailbreak iOS device to add custom beatmaps to the game but instead on a folder that is easily accessible to modify

Possibly in /storage/emulated/0/osu!stream/
or ./Android/data/sh.ppy.osustream/

**Comment by peppy** [comment]
If you build in debug you can load via itunes / finder.
