### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by terrawolf34** [ppy/osu-stream#5]
So on osu stream i have a ui bug Accuracy and score are a Little Offset and rankings too pls fix device:iPhone se 
![D9EE617C-204E-4E77-9847-BA4878EA7C44](https://user-images.githubusercontent.com/59438304/71711790-42e45680-2e0b-11ea-9e67-fe7d049ccaf8.png)
![B75DD41B-1DC0-46E3-999F-26BC2841B5A5](https://user-images.githubusercontent.com/59438304/71711791-437ced00-2e0b-11ea-9e6b-406870031101.png)
![3D596F31-91CD-4E84-A72E-DCE82CC5E656](https://user-images.githubusercontent.com/59438304/71711792-437ced00-2e0b-11ea-98f1-bac63f2353e3.jpeg)

**Comment by peppy** [comment]
Fixed in last release!
