### ISSUE TITLE
How do i compile this for windows?

### ISSUE THREAD

**Issue by Toastyisburning** [ppy/osu-stream#53]
Im trying to get this to work on my pc, but due to my little knowledge in VS, i cant figure out how to compile it.

**Comment by LukaTV939** [comment]
I have a video of how to compile the android version, so try doing the same
for the windows one https://youtu.be/RHH82Gr6aTA

**Comment by Toastyisburning** [comment]
I realized I was using VS code instead of VS, but now I've run into another issue. when I try to build, I get this error. The android and desktop version look a bit different in VS, so there's probably something I'm missing.
![image](https://user-images.githubusercontent.com/50493368/234152087-a5693112-c4b2-434a-a24b-b47a9d226d0f.png)
