### ISSUE TITLE
Notes sometimes almost entirely off-screen

### ISSUE THREAD

**Issue by andrwsmthng** [ppy/osu-stream#6]
I’m using an iPhone 11 on iOS 13.2.2. Beatmap was Nekomimi Switch on Easy. Around 10 seconds in, notes at the bottom of the screen are almost entirely off-screen (and attempting to hit them causes the bottom tab on “home buttonless“ iPhones to activate and pause the app). I sent this same feedback in TestFlight with an image as well.

**Comment by peppy** [comment]
This has been fixed with the latest release!
