### ISSUE TITLE
UI scaling issues on iPhone XR

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu-stream#7]
When playing on the iPhone XR, some of the UI elements are partly offscreen.
![image](https://user-images.githubusercontent.com/10524728/71680664-eec46e00-2d47-11ea-8ff0-5bae7fd86b1e.jpg)

Here the price and pause button are shown in an incorrect position.
![image](https://user-images.githubusercontent.com/10524728/71681296-824a6e80-2d49-11ea-997b-43f44f5d62fa.jpg)

Edit 1: removed info about notes offscreen since an issue already exists

**Comment by peppy** [comment]
These issues should now be resolved.
