### ISSUE TITLE
Certain map packs are not downloadable

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu-stream#8]
When downloading map packs from the store, they are not downloaded correctly. See the [video](https://youtu.be/U-fFVED7_uY) for a better explanation.
(If the video is not viewable, please wait a while for it to upload)

**Comment by peppy** [comment]
Only some? or all?

**Comment by ThatsNiceGuy** [comment]
Most all of them, only the free packs downloaded fine for me

**Comment by peppy** [comment]
Probably specific to the test/sandbox environment then.

**Comment by peppy** [comment]
Closing for now as the packs work correctly on release.

**Comment by ThatsNiceGuy** [comment]
Alright
