### ISSUE TITLE
Spinner position awkward on iPad Pro 12.9

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu-stream#9]
Seems a bit out of place.

![1531CE96-6687-4B74-87F1-2AC15648389F](https://user-images.githubusercontent.com/45163894/74940742-39539400-5435-11ea-8612-6303989ea590.png)

**Comment by peppy** [comment]
Thanks for the report. Does spinning work around the centre of the spinner as expected?

**Comment by Snowmander** [comment]
Yes, the spinning is properly centered at the same place visually.

**Comment by peppy** [comment]
Thanks. I think for the time being I'll consider this a non-critical bug and potentially fix it in the future. Visually it looks a *bit* weird but it has been specifically coded to work that way for more "square" devices.

**Comment by peppy** [comment]
Closing this one as out-of-scope for the time being.
